import type { Metadata } from 'next';

import '@/assets/styles/globals.scss';
import { inter, robotoSlab } from '@/assets/fonts';
import classNames from '../../node_modules/classnames/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={classNames(inter.variable, robotoSlab.variable, 'page')}>{children}</body>
    </html>
  );
}
